
name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: yarn
    - run: yarn build
    - name: Upload js
      uses: actions/upload-artifact@v3
      with:
        name: index.js
        path: dist/index.js
    - name: Upload styling
      uses: actions/upload-artifact@v3
      with:
        name: index.min.css
        path: dist/index.min.css
    - uses: actions-ecosystem/action-push-tag@v1
      with:
        tag: ${{ steps.bump-semver.outputs.new_version }}
    - uses: ncipollo/release-action@v1
      with:
        run: echo ls
        tag: ${{ steps.bump-semver.outputs.new_version }}
        artifacts: "./dist/index.js,./dist/index.min.css"
